apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jsjr-dev-poi-map-app-dev
  annotations:
    argocd/app-name: jsjr-dev-poi-map-app-dev
    backstage.io/kubernetes-id: jsjr-dev-poi-map-app
    backstage.io/kubernetes-namespace: jsjr-dev
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-atl/jsjr-dev-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/dev-pipelines/ns/jsjr-dev/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/k8s/ns/jsjr-dev/deployments/jsjr-dev-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.j0i9yf30.eastus2.aroapp.io/#https://github.com/rhdh-atl/jsjr-dev-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://jsjr-dev-poi-map-app-jsjr-dev.apps.j0i9yf30.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/jsjr-dev"
  system: workshop-system-jsjr-dev
  consumesApis:
    - gateway-api-jsjr-dev
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-jsjr-dev
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/jsjr-dev"
